spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # git\u4ED3\u5E93\u5730\u5740
          uri: https://github.com/CCodingMan/springCloudConfig
          # \u4ED3\u5E93\u8DEF\u5F84
          search-paths: respo
          # \u8BBF\u95EE\u4ED3\u5E93\u7684\u7528\u6237\u540D\uFF0C\u82E5\u4E3A\u516C\u5F00\u5E93\u5219\u53EF\u4E0D\u586B\u5199
          username:
          # \u8BBF\u95EE\u4ED3\u5E93\u7684\u5BC6\u7801\uFF0C\u82E5\u4E3A\u516C\u5F00\u5E93\u5219\u53EF\u4E0D\u586B\u5199
          password:
      # \u4ED3\u5E93\u5206\u652F
      label: master

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
